var L=Object.defineProperty;var v=(e,t,s)=>t in e?L(e,t,{enumerable:!0,configurable:!0,writable:!0,value:s}):e[t]=s;var f=(e,t,s)=>(v(e,typeof t!="symbol"?t+"":t,s),s);import{a as S,S as w,i as m}from"./assets/vendor-b42c18af.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();const c=class c{constructor(){this.BASE_URL="https://pixabay.com/api/",this.END_POINT="",this.query=null,this.page=1,this.totalHits=0}setDefaults(){this.page=1,this.totalHits=0}async getImages(){const t={q:this.query,image_type:"photo",key:"42190247-000e45a6447d3626b5dd5a4c9",orientation:"horizontal",safesearch:!0,page:this.page,per_page:c.PAGE_SIZE},s=`${this.BASE_URL}${this.END_POINT}?${t}`,i=await S.get(s,{params:t});return this.totalHits=i.data.totalHits,i.data}isLastPage(){return Math.ceil(this.totalHits/c.PAGE_SIZE)<=this.page}};f(c,"PAGE_SIZE",15);let u=c;function q(e){return P(e.hits)}function P(e){return e.map(I).join("")}function I(e){const{largeImageURL:t,likes:s,views:i,webformatURL:r,tags:o,comments:l,downloads:E}=e;return`<li class="gallery-item">
    <a class="link-item" href="${t}"><img class="gallery-img" src="${r}" alt="${o}" title=""/></a>
      <div class="info">
        <p class="info-item"><b>Likes</b><br>${s}</p>
        <p class="info-item"><b>Views</b><br>${i}</p>
        <p class="info-item"><b>Comments</b><br>${l}</p>
        <p class="info-item"><b>Downloads</b><br>${E}</p>
      </div>
    </li>`}const n=new u,x=new w(".js-gallery a.link-item",{navText:["←","→"],closeText:"×",enableKeyboard:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250}),a={formEl:document.querySelector('.js-search-form[data-id="1"]'),listEl:document.querySelector(".js-gallery"),inputEl:document.querySelector(".js-input"),loaderEl:document.querySelector(".js-loader"),btnLoader:document.querySelector("#js-btn-load"),targetElem:document.querySelector("#observer")};a.formEl.addEventListener("submit",D);a.btnLoader.addEventListener("click",p);async function D(e){e.preventDefault(),O(),n.setDefaults();let t=e.target.elements.query.value;if(t=t?t.trim():"",t===""){h(),d("Enter correct data!");return}n.query=t,$(),g()}async function p(e){e.preventDefault(),n.page+=1,g()}async function g(){a.loaderEl.style.display="block";try{const e=await n.getImages();if(e.hits.length===0){d("no data on your search query");return}const t=await q(e);a.listEl.insertAdjacentHTML("beforeend",t),x.refresh(),h(),T()}catch{d("An error occurred. Please try again later.")}finally{a.loaderEl.style.display="none"}y()}function O(){a.listEl.innerHTML=""}function $(){a.inputEl.value=null}function d(e){m.error({message:e})}function N(e){m.info({message:e})}function T(){n.isLastPage()&&N("We're sorry, but you've reached the end of search results.")}function h(){n.isLastPage()?a.btnLoader.classList.add("hidden"):a.btnLoader.classList.remove("hidden")}function y(){n.isLastPage()&&b.unobserve(a.targetElem)}const j={root:document.querySelector("#scrollArea"),rootMargin:"0px",threshold:1},k=function(e,t){e.forEach(s=>{s.isIntersecting&&(p(),y())})},b=new IntersectionObserver(k,j);b.observe(a.targetElem);
//# sourceMappingURL=commonHelpers.js.map
