import{a as m,S as f,i as c}from"./assets/vendor-5401a4b0.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();class p{constructor(){this.BASE_URL="https://pixabay.com/api/",this.END_POINT=""}getImages(o){const s={q:o,image_type:"photo",key:"42190247-000e45a6447d3626b5dd5a4c9",orientation:"horizontal",safesearch:!0},i=`${this.BASE_URL}${this.END_POINT}?${s}`;return m.get(i,{params:s}).then(e=>e.data)}}const d=new p,l=new f(".js-gallery a.link-item",{navText:["←","→"],closeText:"×",enableKeyboard:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250}),a={formEl:document.querySelector('.js-search-form[data-id="1"]'),listEl:document.querySelector(".js-gallery"),inputEl:document.querySelector(".js-input"),loaderEl:document.querySelector(".js-loader")};a.formEl.addEventListener("submit",g);async function g(r){r.preventDefault();const o=r.target.elements.query.value;a.loaderEl.style.display="block",E();try{const s=await d.getImages(o);await y(s),l.refresh(),l.on("error.simplelightbox",function(i){console.log(i)})}catch{S()}finally{a.loaderEl.style.display="none",L()}}function y(r){if(r.hits.length===0)return c.error({message:"Sorry, there are no images matching your search query. Please try again!"});{const o=h(r.hits);a.listEl.innerHTML=o}}function h(r){return r.map(b).join("")}function b(r){const{largeImageURL:o,likes:s,views:i,webformatURL:e,tags:t,comments:n,downloads:u}=r;return`<li class="gallery-item">
    <a class="link-item" href="${o}"><img class="gallery-img" src="${e}" alt="${t}" title=""/></a>
      <div class="info">
        <p class="info-item"><b>Likes</b><br>${s}</p>
        <p class="info-item"><b>Views</b><br>${i}</p>
        <p class="info-item"><b>Comments</b><br>${n}</p>
        <p class="info-item"><b>Downloads</b><br>${u}</p>
      </div>
    </li>`}function E(){a.listEl.innerHTML=""}function L(){a.inputEl.value=null}function S(){c.error({message:"An error occurred. Please try again later."})}
//# sourceMappingURL=commonHelpers.js.map
