var E=Object.defineProperty;var L=(e,t,s)=>t in e?E(e,t,{enumerable:!0,configurable:!0,writable:!0,value:s}):e[t]=s;var m=(e,t,s)=>(L(e,typeof t!="symbol"?t+"":t,s),s);import{a as v,S,i as p}from"./assets/vendor-527658dd.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();const c=class c{constructor(){this.BASE_URL="https://pixabay.com/api/",this.END_POINT="",this.query=null,this.page=1,this.totalHits=0}setDefaults(){this.page=1,this.totalHits=0}async getImages(){const t={q:this.query,image_type:"photo",key:"42190247-000e45a6447d3626b5dd5a4c9",orientation:"horizontal",safesearch:!0,page:this.page,per_page:c.PAGE_SIZE},s=`${this.BASE_URL}${this.END_POINT}?${t}`,i=await v.get(s,{params:t});return this.totalHits=i.data.totalHits,i.data}isLastPage(){return Math.ceil(this.totalHits/c.PAGE_SIZE)<=this.page}};m(c,"PAGE_SIZE",60);let u=c;const n=new u,w=new S(".js-gallery a.link-item",{navText:["←","→"],closeText:"×",enableKeyboard:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250}),a={formEl:document.querySelector('.js-search-form[data-id="1"]'),listEl:document.querySelector(".js-gallery"),inputEl:document.querySelector(".js-input"),loaderEl:document.querySelector(".js-loader"),btnLoader:document.querySelector("#js-btn-load"),targetElem:document.querySelector("#observer")};a.formEl.addEventListener("submit",q);async function q(e){e.preventDefault(),D(),n.setDefaults();let t=e.target.elements.query.value;if(t=t?t.trim():"",t===""){y(),d("Enter correct data!");return}n.query=t,O(),h()}a.btnLoader.addEventListener("click",g);async function g(e){e.preventDefault(),n.page+=1,h()}async function h(){a.loaderEl.style.display="block",T();try{const e=await n.getImages();if(e.hits.length===0){d("no data on your search query");return}await P(e),w.refresh(),y(),N()}catch{d("An error occurred. Please try again later.")}finally{a.loaderEl.style.display="none"}}function P(e){const t=I(e.hits);a.listEl.innerHTML+=t}function I(e){return e.map(x).join("")}function x(e){const{largeImageURL:t,likes:s,views:i,webformatURL:r,tags:o,comments:l,downloads:b}=e;return`<li class="gallery-item">
    <a class="link-item" href="${t}"><img class="gallery-img" src="${r}" alt="${o}" title=""/></a>
      <div class="info">
        <p class="info-item"><b>Likes</b><br>${s}</p>
        <p class="info-item"><b>Views</b><br>${i}</p>
        <p class="info-item"><b>Comments</b><br>${l}</p>
        <p class="info-item"><b>Downloads</b><br>${b}</p>
      </div>
    </li>`}function D(){a.listEl.innerHTML=""}function O(){a.inputEl.value=null}function d(e){p.error({message:e})}function $(e){p.info({message:e})}function N(){n.isLastPage()&&$("We're sorry, but you've reached the end of search results.")}function y(){n.isLastPage()?a.btnLoader.classList.add("hidden"):a.btnLoader.classList.remove("hidden")}function T(){n.isLastPage()&&f.unobserve(a.targetElem)}const k={root:document.querySelector("#scrollArea"),rootMargin:"0px",threshold:1},j=function(e,t){e.forEach(s=>{s.isIntersecting&&g()})},f=new IntersectionObserver(j,k);console.log(f);f.observe(a.targetElem);
//# sourceMappingURL=commonHelpers.js.map
